"""
Configuration centralisée du jeu.
Contient toutes les constantes et paramètres du jeu.
"""

import os

# ===== FENÊTRE DE JEU =====
TILE_SIZE = 32
ROW_COUNT = 16
COLUMN_COUNT = ROW_COUNT
GAME_WIDTH = TILE_SIZE * COLUMN_COUNT
GAME_HEIGHT = TILE_SIZE * ROW_COUNT
FPS = 60

# ===== PHYSIQUE =====
GRAVITY = 0.5
FRICTION = 0.4

# ===== JOUEUR (MEGAMAN) =====
PLAYER_START_X = GAME_WIDTH / 2
PLAYER_START_Y = GAME_HEIGHT / 2
PLAYER_WIDTH = 42
PLAYER_HEIGHT = 48
PLAYER_JUMP_WIDTH = 52
PLAYER_JUMP_HEIGHT = 60
PLAYER_SHOOT_WIDTH = 62
PLAYER_JUMP_SHOOT_WIDTH = 58
PLAYER_WALK_WIDTH = 48
PLAYER_WALK_HEIGHT = 48
PLAYER_WALK_SHOOT_WIDTH = 62

PLAYER_VELOCITY_X = 5
PLAYER_VELOCITY_Y = -11  # Vitesse de saut (négative = vers le haut)
PLAYER_MAX_HEALTH = 28

# Animation
PLAYER_ANIMATION_SPEED = 250  # ms entre chaque frame

# ===== PROJECTILES DU JOUEUR =====
PLAYER_BULLET_WIDTH = 16
PLAYER_BULLET_HEIGHT = 12
PLAYER_BULLET_VELOCITY_X = 8
PLAYER_SHOOT_COOLDOWN = 250  # ms

# ===== ENNEMIS =====
# Metall
METALL_WIDTH = 36
METALL_HEIGHT = 30
METALL_HEALTH = 1
METALL_FIRE_RATE = 1000  # ms
METALL_DETECTION_RANGE = TILE_SIZE * 4

# Metall bullets
METALL_BULLET_WIDTH = 12
METALL_BULLET_HEIGHT = 12
METALL_BULLET_VELOCITY_X = 2
METALL_BULLET_VELOCITY_Y = 2

# Blader
BLADER_WIDTH = 32
BLADER_HEIGHT = 40
BLADER_HEALTH = 3
BLADER_VELOCITY_X = 4
BLADER_VELOCITY_Y = 2
BLADER_RANGE_X = TILE_SIZE * 4
BLADER_RANGE_Y = TILE_SIZE

# Gutsman (Boss)
GUTSMAN_WIDTH = 48
GUTSMAN_HEIGHT = 48
GUTSMAN_HEALTH = 20
GUTSMAN_VELOCITY_X = 2
GUTSMAN_JUMP_FORCE = -10
GUTSMAN_GRAVITY = 0.5
GUTSMAN_ATTACK_RANGE = TILE_SIZE * 6
GUTSMAN_THROW_COOLDOWN = 2000  # ms

# ===== ITEMS =====
LIFE_ENERGY_WIDTH = 20
LIFE_ENERGY_HEIGHT = 24
LIFE_ENERGY_HEAL = 2

BIG_LIFE_ENERGY_WIDTH = 28
BIG_LIFE_ENERGY_HEIGHT = 32
BIG_LIFE_ENERGY_HEAL = 8

SCORE_BALL_POINTS = 1000

ITEM_VELOCITY_Y = -11  # Items volent vers le haut puis retombent
ITEM_DROP_CHANCE = 75  # % de chance de drop

# ===== HEALTH BAR =====
HEALTH_WIDTH = 16
HEALTH_HEIGHT = 4
HEALTH_BAR_X = TILE_SIZE
HEALTH_BAR_Y = TILE_SIZE

# ===== INVINCIBILITÉ =====
INVINCIBILITY_DURATION = 1000  # ms

# ===== SCORES =====
ENEMY_KILL_SCORE = 500
SCORE_DIGITS = 7  # Nombre de chiffres à afficher

# ===== CHEMINS DES ASSETS =====
ASSETS_DIR = "images"
FONT_PATH = "megaman-game-font.otf"
FONT_SIZE = 24

# ===== COULEURS =====
COLOR_SKY = (20, 18, 167)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

# ===== TILE MAP CODES =====
TILE_EMPTY = 0
TILE_ROCK1 = 1
TILE_ROCK2 = 2
TILE_ROCK3 = 3
TILE_ROCK4 = 4
TILE_FLOOR = 5
TILE_WALL = 6
TILE_BEAM = 7
TILE_SPIKE = 8
TILE_DOOR = 9
TILE_ROOM = 10
TILE_METALL = 11
TILE_BLADER = 12
TILE_GUTSMAN = 13

# ===== ÉVÉNEMENTS PERSONNALISÉS =====
EVENT_INVINCIBLE_END = 0
EVENT_SHOOTING_END = 1
EVENT_ENEMY_DEFEATED = 2
EVENT_ITEM_COLLECTED = 3
EVENT_PLAYER_HIT = 4
EVENT_LEVEL_COMPLETE = 5
